spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ""
    username: ""
    password: ""
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt